services:
  - type: web
    name: housing-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && python main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: housing_management_secret_key_2025_production
    healthCheckPath: /

